name: CD Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "Nguyenduyhai2004" | docker login -u "hainguyenduy2004" --password-stdin
  

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: 3.25.82.59
        username: ubuntu
        key: -----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEAkFGVeUMXDThBJ5+z/SFm+8TmhjjleC89nDYPZRpN6f0Kg3h9
          OI8d/vRn/ql6Rsiu1v+wEmw9t5jm/q+LW9GvzWD65Sw2sJRLhpL2uyDf8KD65IpD
          m4mYAc3iQ750h5AsDGPcr50U7G6l6Is4iiDVM3jCd3ASrt/7fya+3urg1nmeP3Qb
          fhCpZiJ5E93TazTVvI/zvIR8LF55Yrn+78lgFdZkzDjxoF4TVPO4HM12ILIXlzIE
          u1uuj+9JSR0JBkcz/nj+Zk3wbVhtWfcIS4eMaQxHmq2Z2oBAcvIQU368KNjLw0aH
          owVYtAwprgcXuFg106MjWf8FHyH12imT6DbgKQIDAQABAoIBAH5wm+6z0txoLt1S
          VFUwEJQAfJ+X9aOIcAgObQp9M0oPwkhRJhSJfxRCeWJqhZDCfjwro81gO+pA8hCt
          KAF4AviDQQ3L4NZv9oOe+sAUG18tCuN0J6t7r0vVX6lOkbW7oHvyegT6MLy8bGsC
          nrSV83S3FlmiPRwtbKCIB64yRm5gqUDnCamWoR1+bEUZJ6qGmPFQxAW4RgN0jbB9
          p1Mm4wdC5wZ8UkucV1B58WsE+jwhXMaPx+VZ1aDT7BkYyhiJHsZJ+j61RswIwIXt
          QgFfES3/XenUylO0hnp7QADdl0dXfpbMcLpVwYEc9l1YiqN3iIpF6ZpgNNx3T90u
          v2bo9gECgYEA0Qd1Yd7tD0Jd8r91dWfSz/XXqx1jNUaD7ZsVWgAEDO2dea+9lxbn
          wqkmMEnQMMbvm7iSllew0sF8hCw5YiKFr0XfzZMVhf4b2hC36xTctja5Vlpt9MvZ
          wVCxYJNeJYb46L0ainfxlNNp9xK7LV1F+YCMOYZKA44OF1a4X9roxEkCgYEAsL+d
          BK7E9lCaz873ZL88zht+5XrBhtWc+j1jEaruHFWXuS2tRt3AmVv/mbCPDOaSI/Kc
          w1G+zT3udFZox0L50KAyrYJjqm0rfN2XgBeRmVU2yqcPKXbp74CNReVAN3KKEb1C
          5iQVhcQoyQb3T3dfi+tNQSjP9z8lmEfLESAXfOECgYEAtCuyoOaO/Q0ef4NJ0iXo
          jvn/qG2POreKNb7r+4Rx+VbC2sWBLH9AywgTc6HcAn8mvtmr+EyjjDXchuy7lXve
          MQKQctipv7IU/bRVYxq7V4/51pXhmxQuoLNWAMFlcAFUAQAmpV3XbImCF8YccnCo
          RPPpahf3KfNC8Bj+mRjOc4kCgYBNzbtf4VMgnnDXg2LRvYEVtXLRr4zbPtMgML+Y
          embgoCjuwhWhuWHb4GyOifMemazBGD47mJNmI5oBKjxrYqc3WB2W1WvsDKx1BdJ3
          92gHWESLRqjc9tSZsjv+BaGUBt6SWn7FciLrRGMzwtZA6+pqXEUgpseNLgXtl8Tj
          H/5W4QKBgQCaylrTLtabzQpZDbRuv85dsOdSOOzG66s5mP3qRukIoUWxTDgusb80
          snmSkJHYxI28LTWIOO4JLaWSZYEmX2PLamnUf5OPlfjI3BOE85XY/M9vgwCfX1ZH
          gffLiTEJ1chGH5mKRu587d4Y7OJBBPeRSPUKfRG1RIHOPISKVMTDwg==
          -----END RSA PRIVATE KEY-----
        script: |
          sudo docker pull hainguyenduy2004/demo:v4
          sudo docker stop v4-container || true
          sudo docker rm v4-container || true
          sudo docker run -d --name v4-container -p 80:3000 hainguyenduy2004/demo:v4
