name: CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: 3.25.82.59
        username: NguyenDuyHai
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull hainguyenduy2004/demo:v4

          docker stop v4-container || true
          docker rm v4-container || true

          docker run -d --name v4-container -p 80:3000 hainguyenduy2004/demo:v4
