name: CD Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "Nguyenduyhai2004" | docker login -u "hainguyenduy2004" --password-stdin
  

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: 3.25.82.59
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker pull hainguyenduy2004/demo:v4
          sudo docker stop v4-container || true
          sudo docker rm v4-container || true
          sudo docker run -d --name v4-container -p 80:3000 hainguyenduy2004/demo:v4
